service: iaTweetBot

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  timeout: 30
  environment:
    CONSUMER_API_KEY: ${ssm:/iaTweetBot_twitter_consumerKey}
    CONSUMER_API_SECRET: ${ssm:/iaTweetBot_twitter_consumerSecret}
    ACCESS_TOKEN: ${ssm:/iaTweetBot_twitter_accessToken}
    ACCESS_TOKEN_SECRET: ${ssm:/iaTweetBot_twitter_accessTokenSecret}

functions:
  iaTweetBot:
    handler: handler.iaTweetBot
    events:
      - schedule: rate(10 minutes)